[package]
name = "jjinx"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version="1", features=["full"]}
tokio-util = "0.7"
thiserror = "1.0"
indoc = "1.0"
itoa = "1.0"
futures = "0.3"
regex = "1"
twox-hash = "1"
scopeguard = "1"
lockfree = "0.5"
rustls = "0.23"
rustls-pemfile = "2"
tokio-rustls = "0.26"
