server {
    default

    route = / {
        file index.html
    }

    route ^~ /index.html {
        file index.html
    }

    route ~ .* {
        status 404
    }

    route ^~ /test {
        header X-Test $http_user_agent
    }
}
