upstream round_robin {
    round_robin
    server localhost:8000
    server localhost:8001
}

upstream least_conn {
    least_conn
    server localhost:8000
    server localhost:8001
}

upstream ip_hash {
    ip_hash
    server localhost:8000
    server localhost:8001
}

server {
    port 8080
    default

    route = / {
        file index.html
    }

    route /index.html {
        file index.html
    }

    route /get-host {
        body "Host: $host\n"
    }

    route /example-proxy {
        proxy http://localhost:8000
    }

    route /path-proxy/ {
        proxy http://localhost:8000/api/
    }

    route /round-robin {
        proxy http://round_robin
    }

    route /least-conn {
        proxy http://least_conn
    }

    route /ip-hash {
        proxy http://ip_hash
    }

    route /https-proxy {
        proxy https://example.com:443
        proxy_header Host example.com
    }

    route /404 {
        body "Not found"
    }

    error_page 404 /404
}

server {
    port 4433
    default

    ssl_cert server.crt
    ssl_keys server.key

    route / {
        proxy http://localhost:8080
    }
}
